entryPoints:
  web:
    address: ":80"
  dashboard:
    address: ":8080"

api:
  dashboard: true
  insecure: true  # ⚠️ for local only, remove in production

providers:
  docker:
    exposedByDefault: false
