# traefik/certs/traefik.yml
# traefik.yml
log:
  level: DEBUG
entryPoints:
  web:
    address: ":80"
  dashboard:
    address: ":8080"
  websecure:
    address: ":443"

api:
  dashboard: true
  insecure: true  # ⚠️ for local only, remove in production

providers:
  docker:
    exposedByDefault: false
  file:
    filename: /etc/traefik/dynamic/traefik_dynamic.yml
    watch: true