# kong.yml
_format_version: "3.0"
_transform: true

services:
  - name: n8n-webhook-service
    url: http://n8n:5678
    tags:
      - n8n
# routes:
#   - name: n8n-webhook-route
#     service: n8n-webhook-service
#     paths:
#       - /webhooks
#     methods:
#       - POST
#       - GET
#       - OPTIONS
#     strip_path: true
#     tags:
#       - webhook

# plugins:
#   - name: cors
#     route: n8n-webhook-route
#     config:
#       origins:
#         - "*"
#       methods:
#         - GET
#         - POST
#         - OPTIONS
#       headers:
#         - Content-Type
#         - Authorization
#       credentials: false
#       max_age: 3600
