version: '3.8'

networks:
  helix-net:
    external: false
  default:
    external: false

volumes:
  helix_db_data:
  n8n_data:
  filebrowser_data:

services:
  # Core Services
  postgres:
    profiles: ["core", "lms", "ecommerce"]
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: helix_db
      POSTGRES_USER: helix_user
      POSTGRES_PASSWORD: helix_pass
    volumes:
      - helix_db_data:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - helix-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U helix_user -d helix_db"]
      interval: 30s
      timeout: 10s
      retries: 3

  n8n:
    profiles: ["core", "integration"]
    image: n8nio/n8n:latest
    ports:
      - "5678:5678"
    environment:
      N8N_HOST: localhost
      N8N_PORT: 5678
      N8N_PROTOCOL: http
      NODE_ENV: production
      WEBHOOK_URL: http://localhost:5678/
      GENERIC_TIMEZONE: UTC
    volumes:
      - n8n_data:/home/node/.n8n
      - ./n8n/config.json:/home/node/.n8n/config.json:ro
    networks:
      - helix-net
    depends_on:
      postgres:
        condition: service_healthy

  filebrowser:
    profiles: ["core"]
    image: filebrowser/filebrowser:latest
    ports:
      - "8082:80"
    volumes:
      - filebrowser_data:/srv
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      FB_DATABASE: /srv/filebrowser.db
    networks:
      - helix-net
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  sftp-demo:
    profiles: ["core"]
    image: atmoz/sftp:latest
    command: bank:bankpassword:1001
    networks:
      - helix-net
